package Constant

var UserAgent = []string{
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_3_9; en-US) Gecko/20100101 Firefox/57.9",
	"Mozilla/5.0 (iPod; CPU iPod OS 10_9_1; like Mac OS X) AppleWebKit/603.38 (KHTML, like Gecko)  Chrome/50.0.3772.339 Mobile Safari/602.6",
	"Mozilla/5.0 (Windows; U; Windows NT 10.0; WOW64; en-US) AppleWebKit/533.47 (KHTML, like Gecko) Chrome/49.0.3781.290 Safari/600.2 Edge/15.92147",
	"Mozilla/5.0 (Windows; U; Windows NT 10.5; WOW64; en-US) Gecko/20100101 Firefox/62.4",
	"Mozilla/5.0 (Linux; Android 7.1.1; Nexus 8 Build/NME91E) AppleWebKit/601.14 (KHTML, like Gecko)  Chrome/55.0.2800.145 Mobile Safari/603.0",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 7_5_9) Gecko/20100101 Firefox/50.7",
	"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_10_3; en-US) Gecko/20100101 Firefox/60.0",
	"Mozilla/5.0 (Windows; U; Windows NT 10.1; x64) AppleWebKit/601.36 (KHTML, like Gecko) Chrome/47.0.1746.347 Safari/534",
	"Mozilla/5.0 (Windows; Windows NT 10.4; WOW64) AppleWebKit/601.8 (KHTML, like Gecko) Chrome/55.0.2844.260 Safari/533.7 Edge/17.19353",
	"Mozilla/5.0 (Windows; Windows NT 6.3; Win64; x64; en-US) Gecko/20130401 Firefox/47.5",
}

var TechnologyHeaders = []string{
	"Server",
	"X-Powered-By",
	"X-Generator",
	"X-Drupal-Cache",
	"X-Drupal-Dynamic-Cache",
	"X-Varnish",
	"X-Shopify-Stage",
	"X-WP-Total",
	"X-WP-TotalPages",
	"X-Pingback",
	"link",
	"X-Magento-Cache-Debug",
	"X-Magento-Tags",
	"CF-Cache-Status",
	"CF-Ray",
	"X-Sucuri-ID",
	"X-Akamai-Transformed",
	"X-CDN",
	"X-Amz-Cf-Id",
	"Via",
	//"X-Cache",
	//"X-Cache-Hits",
	//"X-Served-By",
	"X-Edge-Location",
	"X-Rails-Version",
	"X-Rack-Cache",
	"X-Django-Version",
	"X-AspNet-Version",
	"X-AspNetMvc-Version",
	"X-Powered-CMS",
	"X-React-Version",
	"X-Vue-Version",
	"X-Angular-Version",
	"X-DB-Server",
	"X-MongoDB-Server",
	"X-Cassandra-Version",
	"X-PHP-Version",
	"X-Node-Version",
	"X-Python-Version",
	"X-Ruby-Version",
	"X-RateLimit-Limit",
	"X-RateLimit-Remaining",
	"X-API-Version",
	"X-CSRF-Token",
	"X-Cache-Control",
	//"X-Content-Type-Options",
	//"X-Frame-Options",
	//"X-XSS-Protection",
	//"Etag",
	"X-Request-ID",
	"X-Runtime",
	"X-Response-Time",
	"X-Wix-Request-ID",
	"X-Wix-Renderer-Server",
	"X-Shopify-API-Version",
	"X-PrestaShop-Cache",
	"X-Shopware-Cache-Id",
	"X-Kubernetes-Backend",
	"X-Docker-Registry-Version",
	"X-Jenkins-Version",
	"X-Heroku-Dynos",
	"X-Azure-Ref",
	"X-Vercel-Id",
	"X-Netlify",
	"X-AWS-Details",
	"X-Google-Cloud",
	"X-Litespeed-Cache",
	"X-Proxy-Cache",
	"X-Debug",
	"X-GTM-Server-Preview",
	"X-Tracking-Ref",
	"X-Image-Processing",
	"X-Imagizer",
	"X-Thumbor",
	"X-WAF-UUID",
	"X-ModSecurity",
	"X-Firewall-Blocked",
	"X-GeoIP-Country",
	"X-Country-Code",
	"X-Accept-Language",
	"X-Crawler-Detected",
	"X-Robots-Tag",
	//"Strict-Transport-Security",
	"Public-Key-Pins",
	"Content-Security-Policy",
	"Expect-CT",
	//"Vary",
	"X-UA-Compatible",
	"Access-Control-Allow-Origin",
	//"Accept-Ranges",
	//"Alt-Svc",ff
	//"Referrer-Policy",
	//"Permissions-Policy",
	"Timing-Allow-Origin",
	"set-cookie",
}
var CookieTechMap = map[string]string{
	"PHPSESSID":             "PHP",
	"ASP.NET_SessionId":     "ASP.NET",
	"NID":                   "Google Servisleri",
	"__cfduid":              "Cloudflare",
	"_ga":                   "Google Analytics",
	"_gid":                  "Google Analytics",
	"_gat":                  "Google Analytics",
	"SID":                   "Google Oturum",
	"HSID":                  "Google Oturum",
	"SSID":                  "Google Oturum",
	"csrftoken":             "Django",
	"sessionid":             "Django",
	"laravel_session":       "Laravel",
	"XSRF-TOKEN":            "Laravel / Angular",
	"ci_session":            "CodeIgniter",
	"rack.session":          "Ruby on Rails",
	"_rails_session":        "Ruby on Rails",
	"PLAY_SESSION":          "Play Framework (Scala/Java)",
	"connect.sid":           "Express.js",
	"express.sid":           "Express.js (eski)",
	"wp-settings-*":         "WordPress",
	"wordpress_logged_in_*": "WordPress",
	"ZSESSIONID":            "Oracle Zimbra",
	"NSC_*":                 "Citrix NetScaler",
	"BCSI-*":                "Blue Coat Proxy",
	"ajs_user_id":           "Segment.io",
	"ajs_group_id":          "Segment.io",
	"JSESSIONID":            "Java (Servlet / JSP)",
}

var CDNPatterns = map[string]struct {
	Patterns    []string
	Description string
}{
	"Cloudflare": {
		Patterns: []string{
			`cloudflare\.com`,
			`cdnjs\.cloudflare\.com`,
			`cdn\.cloudflare\.net`,
			`cdn-cgi/`,
			`cloudflare-static`,
		},
	},
	"Akamai": {
		Patterns: []string{
			`akamai\.net`,
			`akamaihd\.net`,
			`akamaized\.net`,
			`akamaitechnologies\.com`,
			`akadns\.net`,
		},
	},
	"Fastly": {
		Patterns: []string{
			`fastly\.net`,
			`fastlylb\.net`,
			`fastly-terrarium`,
			`fastly\.com`,
		},
	},
	"Amazon CloudFront": {
		Patterns: []string{
			`cloudfront\.net`,
			`amazonaws\.com/.*cloudfront`,
		},
	},
	"jsDelivr": {
		Patterns: []string{
			`cdn\.jsdelivr\.net`,
			`jsdelivr\.com`,
			`jsdelivr\.net`,
		},
	},
	"UNPKG": {
		Patterns: []string{
			`unpkg\.com`,
		},
	},
	"Google CDN": {
		Patterns: []string{
			`googleapis\.com`,
			`googleusercontent\.com`,
			`googlevideo\.com`,
			`gstatic\.com`,
			`ajax\.googleapis\.com`,
		},
	},
	"Microsoft CDN": {
		Patterns: []string{
			`aspnetcdn\.com`,
			`msecnd\.net`,
			`ajax\.aspnetcdn\.com`,
			`static\.microsoft\.com`,
		},
	},
	"StackPath": {
		Patterns: []string{
			`stackpathdns\.com`,
			`stackpath\.com`,
			`netdna-cdn\.com`, // Acquired MaxCDN
			`netdna-ssl\.com`,
			`stackpathcdn\.com`,
		},
	},
	"Bunny CDN": {
		Patterns: []string{
			`bunnycdn\.com`,
			`b-cdn\.net`,
		},
	},
	"Edgio": {
		Patterns: []string{
			`edgio\.net`,
			`edgio\.io`,
			`limelight\.com`,
			`llnwd\.net`, // Limelight Networks (now Edgio)
		},
	},
	"Vercel": {
		Patterns: []string{
			`vercel\.com`,
			`vercel\.app`,
			`now\.sh`,
		},
	},
	"Netlify": {
		Patterns: []string{
			`netlify\.com`,
			`netlify\.app`,
		},
	},
	"jQuery CDN": {
		Patterns: []string{
			`code\.jquery\.com`,
		},
	},
	"cdnjs": {
		Patterns: []string{
			`cdnjs\.com`,
		},
	},
}

var SoftwareType = map[string]string{
	"SmartMenus jQuery Plugin":  "jquery-smartmenu",
	"Respond.js":                "respond.js",
	"Hammer.JS":                 "hammerjs",
	"enquire.js":                "enquire.js",
	"normalize.css":             "normalize.css",
	"jQuery Validation Plugin":  "jquery-validation",
	"JSZip":                     "jszip",
	"pdfmake":                   "pdfmake",
	"jquery.cookie":             "jquery.cookie",
	"sweetalert2":               "sweetalert2",
	"jQuery JavaScript Library": "jquery",
	"Bootstrap":                 "bootstrap",
	"jQuery UI":                 "jquery-ui",
	"Owl Carousel":              "owl.carousel",
	"fancyBox":                  "@fancyapps/fancybox",
	"jQuery":                    "jquery",
	"jQuery Browser Plugin":     "jquery.browser",
	"jQuery pagination plugin":  "jq-pagination",
	"Colorbox":                  "jquery-colorbox",
	"carousel.js":               "carousel-js",
	"Spectrum Colorpicker":      "spectrum-colorpicker",
	"Font Awesome":              "font-awesome",
}

var TechList = []string{
	"jQuery",
	"React",
	"Vue.js",
	"Angular",
	"Svelte",
	"Alpine.js",
	"Backbone.js",
	"jQuery Browser Plugin",
	"Bootstrap",
	"Tailwind CSS",
	"Bulma",
	"Foundation",
	"Materialize",
	"normalize.css",
	"Animate.css",
	"Font Awesome",
	"Material Icons",
	"Modernizr",
	"RequireJS",
	"Moment.js",
	"Colorbox",
	"Select2",
	"Swiper",
	"DataTables",
	"jQuery UI",
	"Lightbox",
	"Chart.js",
	"D3.js",
	"FullCalendar",
	"PHP",
	"Laravel",
	"Symfony",
	"CodeIgniter",
	"ASP.NET",
	"Express",
	"Node.js",
	"Django",
	"Flask",
	"Ruby on Rails",
	"Spring Boot",
	"Go",
	"FastAPI",
	"NestJS",
	"WordPress",
	"Joomla",
	"Drupal",
	"Shopify",
	"Wix",
	"Blogger",
	"Magento",
	"Ghost",
	"Nginx",
	"Apache",
	"LiteSpeed",
	"IIS",
	"Cloudflare",
	"Google Analytics",
	"Hotjar",
	"Facebook Pixel",
	"Matomo",
	"Vercel",
	"Netlify",
}
